services:
  client:
    build: ./client
    restart: always
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_USE_POLLING=true
    ports:
      - "5173:5173"
    depends_on:
      - server

  server:
    build: ./server
    restart: always
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=todolist
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: todolist
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: "123"
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025" # SMTP Port

volumes:
  dbdata:
  client_node_modules:
  server_node_modules:
